#[cfg(feature = "gfx")]
pub mod gfx;
#[cfg(feature = "sfx")]
pub mod sfx;
#[cfg(feature = "synth")]
pub mod synth;
#[cfg(feature = "fs")]
pub mod fs;
#[cfg(feature = "midi")]
pub mod midi;

#[cfg(feature = "gfx")]
pub use gfx::GfxPlugin;
#[cfg(feature = "sfx")]
pub use sfx::SfxPlugin;
#[cfg(feature = "synth")]
pub use synth::SynthPlugin;
#[cfg(feature = "fs")]
pub use fs::FsPlugin;
#[cfg(feature = "midi")]
pub use midi::MidiPlugin;
